/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.insurance_coverage;

/**
 *
 * @author YAGNIK
 */


public class insuranceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form insuranceJPanel
     */
    
    insurance_coverage insurancecover;
    public insuranceJPanel(insurance_coverage insurancecover) {
        initComponents();
        this.insurancecover = insurancecover;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpremium = new javax.swing.JTextField();
        txtdeductable = new javax.swing.JTextField();
        lblgpslocation = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        txtcorporateid = new javax.swing.JTextField();
        txtcompanyname = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        lblcountry = new javax.swing.JLabel();
        lblcountry1 = new javax.swing.JLabel();
        txtcoveragetype = new javax.swing.JTextField();
        lblcountry2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbenefit = new javax.swing.JTextArea();
        lbladdress = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnsave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblgpslocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblgpslocation.setText("Corporate ID number");

        lblcity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcity.setText("Company name");

        txtcorporateid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorporateidActionPerformed(evt);
            }
        });

        lblstate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblstate.setText("premium");

        lblcountry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcountry.setText("Deductable");

        lblcountry1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcountry1.setText("Coverage type");

        lblcountry2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcountry2.setText("Benefits");

        txtbenefit.setColumns(20);
        txtbenefit.setRows(5);
        jScrollPane1.setViewportView(txtbenefit);

        lbladdress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbladdress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladdress.setText("Insurance coverage");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbladdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcountry2)
                                    .addComponent(lblcountry1))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcoveragetype)
                                    .addComponent(jScrollPane1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcity)
                                    .addComponent(lblgpslocation)
                                    .addComponent(lblcountry)
                                    .addComponent(lblstate))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpremium, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtdeductable)
                                    .addComponent(txtcompanyname)
                                    .addComponent(txtcorporateid, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(152, 152, 152))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(btnsave)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbladdress)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblgpslocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblcity))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcorporateid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdeductable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcoveragetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcountry1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcountry2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsave)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcorporateidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorporateidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorporateidActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        insurancecover.setCorpid(txtcorporateid.getText());
        insurancecover.setComname(txtcompanyname.getText());
        insurancecover.setPremium(txtpremium.getText());
        insurancecover.setDeductable(txtdeductable.getText());
        insurancecover.setCoveragetype(txtcoveragetype.getText());
        insurancecover.setBenefit(txtbenefit.getText());
        
        
        JOptionPane.showMessageDialog(this,"saved successfully.");
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblcountry;
    private javax.swing.JLabel lblcountry1;
    private javax.swing.JLabel lblcountry2;
    private javax.swing.JLabel lblgpslocation;
    private javax.swing.JLabel lblstate;
    private javax.swing.JTextArea txtbenefit;
    private javax.swing.JTextField txtcompanyname;
    private javax.swing.JTextField txtcorporateid;
    private javax.swing.JTextField txtcoveragetype;
    private javax.swing.JTextField txtdeductable;
    private javax.swing.JTextField txtpremium;
    // End of variables declaration//GEN-END:variables
}
