/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.Person;
import model.Driver;
import model.address;
import model.doctor;
import model.insurance_coverage;
import model.patient;
import model.vehicle_registration;


/**
 *
 * @author YAGNIK
 */

public class MainJFrame extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form MainJFrame
     */
    
    Person person;
    Driver driver;
    address address;
    insurance_coverage insurancecover;
    patient patient;
    vehicle_registration vehicle;
    doctor doctor;

    
    public MainJFrame() {
        initComponents();
        
        driver = new Driver();
        person = new Person();
        address = new address();
        vehicle = new vehicle_registration();
        patient = new patient();
        doctor = new doctor();
        insurancecover = new insurance_coverage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlpanel = new javax.swing.JPanel();
        btnperson = new javax.swing.JButton();
        btndriver = new javax.swing.JButton();
        btnvehicleregistration = new javax.swing.JButton();
        btnpatient = new javax.swing.JButton();
        btndisplaypatientreport = new javax.swing.JButton();
        btnaddress = new javax.swing.JButton();
        btndoctor = new javax.swing.JButton();
        btninsurancecoverage = new javax.swing.JButton();
        workarea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        controlpanel.setBackground(new java.awt.Color(204, 204, 204));

        btnperson.setText("person");
        btnperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonActionPerformed(evt);
            }
        });

        btndriver.setText("driver");
        btndriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndriverActionPerformed(evt);
            }
        });

        btnvehicleregistration.setText("vehicle");
        btnvehicleregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvehicleregistrationActionPerformed(evt);
            }
        });

        btnpatient.setText("patient");
        btnpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientActionPerformed(evt);
            }
        });

        btndisplaypatientreport.setText("display report");
        btndisplaypatientreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndisplaypatientreportActionPerformed(evt);
            }
        });

        btnaddress.setText("address");
        btnaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddressActionPerformed(evt);
            }
        });

        btndoctor.setText("Doctor");
        btndoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoctorActionPerformed(evt);
            }
        });

        btninsurancecoverage.setText("insurance coverage");
        btninsurancecoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsurancecoverageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlpanelLayout = new javax.swing.GroupLayout(controlpanel);
        controlpanel.setLayout(controlpanelLayout);
        controlpanelLayout.setHorizontalGroup(
            controlpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnperson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btninsurancecoverage)
                    .addComponent(btndisplaypatientreport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnvehicleregistration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        controlpanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btndoctor, btninsurancecoverage});

        controlpanelLayout.setVerticalGroup(
            controlpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnperson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvehicleregistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnaddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btninsurancecoverage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btndisplaypatientreport)
                .addContainerGap())
        );

        controlpanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btndisplaypatientreport, btndriver, btnpatient, btnperson, btnvehicleregistration});

        controlpanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btndoctor, btninsurancecoverage});

        jSplitPane1.setLeftComponent(controlpanel);

        workarea.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout workareaLayout = new javax.swing.GroupLayout(workarea);
        workarea.setLayout(workareaLayout);
        workareaLayout.setHorizontalGroup(
            workareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        workareaLayout.setVerticalGroup(
            workareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(workarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndriverActionPerformed
        // TODO add your handling code here:
        driverJPanel driverpanel = new driverJPanel(driver);
        jSplitPane1.setRightComponent(driverpanel);
    }//GEN-LAST:event_btndriverActionPerformed

    private void btnpersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonActionPerformed
        // TODO add your handling code here:
        personJPanel personpanel = new personJPanel(person);
        jSplitPane1.setRightComponent(personpanel);
        
    }//GEN-LAST:event_btnpersonActionPerformed

    private void btnaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddressActionPerformed
        // TODO add your handling code here:
        addressJPanel addresspanel = new addressJPanel(address);
        jSplitPane1.setRightComponent(addresspanel);
    }//GEN-LAST:event_btnaddressActionPerformed

    private void btnvehicleregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvehicleregistrationActionPerformed
        // TODO add your handling code here:
        vehicleregistrationJPanel vehiclepanel = new vehicleregistrationJPanel(vehicle);
        jSplitPane1.setRightComponent(vehiclepanel);
    }//GEN-LAST:event_btnvehicleregistrationActionPerformed

    private void btnpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientActionPerformed
        // TODO add your handling code here:
        patientJPanel patientpanel = new patientJPanel(patient);
        jSplitPane1.setRightComponent(patientpanel);
    }//GEN-LAST:event_btnpatientActionPerformed

    private void btndoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoctorActionPerformed
        // TODO add your handling code here:
        doctorJPanel doctorpanel = new doctorJPanel(doctor);
        jSplitPane1.setRightComponent(doctorpanel);
    }//GEN-LAST:event_btndoctorActionPerformed

    private void btninsurancecoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsurancecoverageActionPerformed
        // TODO add your handling code here:
        insuranceJPanel insurancepanel = new insuranceJPanel(insurancecover);
        jSplitPane1.setRightComponent(insurancepanel);
    }//GEN-LAST:event_btninsurancecoverageActionPerformed

    private void btndisplaypatientreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndisplaypatientreportActionPerformed
        // TODO add your handling code here:
        patientreportJPanel patientreportpanel = new patientreportJPanel(person, driver,address,insurancecover,patient,vehicle, doctor);
        jSplitPane1.setRightComponent(patientreportpanel);
    }//GEN-LAST:event_btndisplaypatientreportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddress;
    private javax.swing.JButton btndisplaypatientreport;
    private javax.swing.JButton btndoctor;
    private javax.swing.JButton btndriver;
    private javax.swing.JButton btninsurancecoverage;
    private javax.swing.JButton btnpatient;
    private javax.swing.JButton btnperson;
    private javax.swing.JButton btnvehicleregistration;
    private javax.swing.JPanel controlpanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workarea;
    // End of variables declaration//GEN-END:variables
}
