/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Person;
import model.Driver;
import model.address;
import model.insurance_coverage;
import model.patient;
import model.vehicle_registration;
import model.doctor;


/**
 *
 * @author YAGNIK
 */
public class patientreportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form patientreportJPanel
     */
    Person person;
    Driver driver;
    address address;
    insurance_coverage insurancecover;
    patient patient;
    vehicle_registration vehicle;
    doctor doctor;
    
    
    public patientreportJPanel(Person person, Driver driver, address address, insurance_coverage insurancecover, patient patient, vehicle_registration vehicle, doctor doctor) {
        initComponents();
        
        this.person = person;
        displayperson();
        
        this.driver = driver;
        displaydriver();
        
        this.address = address;
        displayaddress();
        
        this.insurancecover = insurancecover;
        displayinsurancecover();
        
        this.patient = patient;
        displaypatient();
        
        this.vehicle = vehicle;
        displayvehicle();
        
        this.doctor = doctor;
        displaydoctor();
        
    }

//    patientreportJPanel(Person person, Driver driver, doctor doctor, address address, vehicle_registration vehicle, insurance_coverage insurancecover, patient patient) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lbladdress = new javax.swing.JLabel();
        txtcontactnumber = new javax.swing.JTextField();
        lblwebsiteurl = new javax.swing.JLabel();
        txtwebsiteurl = new javax.swing.JTextField();
        lblfirstname = new javax.swing.JLabel();
        txtdateofbirth = new javax.swing.JTextField();
        lbldateofbirth = new javax.swing.JLabel();
        txtoccupation = new javax.swing.JTextField();
        lblgender = new javax.swing.JLabel();
        txtnationality = new javax.swing.JTextField();
        lbloccupation = new javax.swing.JLabel();
        lblnationality = new javax.swing.JLabel();
        lblperson1 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        lbllastname = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblcontactnumber = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();
        lblssn = new javax.swing.JLabel();
        lblgpslocation = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        txtgpslocation = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        lblcountry = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        txtcountry = new javax.swing.JTextField();
        txtdriverlicence = new javax.swing.JTextField();
        lbldriver = new javax.swing.JLabel();
        lbldriverlicence = new javax.swing.JLabel();
        lblserial = new javax.swing.JLabel();
        txtserial = new javax.swing.JTextField();
        lblvehicletype = new javax.swing.JLabel();
        txtvehicletype = new javax.swing.JTextField();
        txtmodel = new javax.swing.JTextField();
        lblvehicle = new javax.swing.JLabel();
        lblregistration = new javax.swing.JLabel();
        lblregistrationdate = new javax.swing.JLabel();
        txtregistrationno = new javax.swing.JTextField();
        txtregistrationdate = new javax.swing.JTextField();
        lblmodel = new javax.swing.JLabel();
        lblcountry1 = new javax.swing.JLabel();
        txtcoveragetype = new javax.swing.JTextField();
        lblcountry2 = new javax.swing.JLabel();
        txtpremium = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbenefits = new javax.swing.JTextArea();
        txtdeductable = new javax.swing.JTextField();
        lblgpslocation1 = new javax.swing.JLabel();
        lbladdress2 = new javax.swing.JLabel();
        lblcity1 = new javax.swing.JLabel();
        txtcorporateid = new javax.swing.JTextField();
        txtcompanyname = new javax.swing.JTextField();
        lblwebsiteurl1 = new javax.swing.JLabel();
        lbldateofbirth1 = new javax.swing.JLabel();
        lblcontactnumber1 = new javax.swing.JLabel();
        txtlastvisit = new javax.swing.JTextField();
        lblstate1 = new javax.swing.JLabel();
        lblcountry3 = new javax.swing.JLabel();
        lblssn1 = new javax.swing.JLabel();
        txtnextapp = new javax.swing.JTextField();
        lbladdress1 = new javax.swing.JLabel();
        lblcontactnumber2 = new javax.swing.JLabel();
        txtpatientid = new javax.swing.JTextField();
        lblcontactnumber3 = new javax.swing.JLabel();
        txtinsurancecover = new javax.swing.JTextField();
        lblcontactnumber4 = new javax.swing.JLabel();
        txtprimarydoc = new javax.swing.JTextField();
        txtallergies = new javax.swing.JTextField();
        txtmedicate = new javax.swing.JTextField();
        txtdocfirst = new javax.swing.JTextField();
        txtdoclast = new javax.swing.JTextField();
        lblperson2 = new javax.swing.JLabel();
        txtofficeadd = new javax.swing.JTextField();
        lblcontactnumber5 = new javax.swing.JLabel();
        lbllastname1 = new javax.swing.JLabel();
        txtdoccontactnumber = new javax.swing.JTextField();
        lblemail1 = new javax.swing.JLabel();
        txtdocemail = new javax.swing.JTextField();
        lblemail2 = new javax.swing.JLabel();
        lblfirstname1 = new javax.swing.JLabel();
        lblspeciality = new javax.swing.JLabel();
        lbloccupation1 = new javax.swing.JLabel();
        txtdocspeciality = new javax.swing.JTextField();
        txtdoctorid = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setAutoscrolls(true);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbladdress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbladdress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladdress.setText("Address");

        lblwebsiteurl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblwebsiteurl.setText("Website URL");

        lblfirstname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblfirstname.setText("First name");

        lbldateofbirth.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldateofbirth.setText("Date of birth");

        lblgender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblgender.setText("Gender");

        txtnationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnationalityActionPerformed(evt);
            }
        });

        lbloccupation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbloccupation.setText("Occupation");

        lblnationality.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblnationality.setText("Nationality");

        lblperson1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblperson1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblperson1.setText("Person");

        lbllastname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbllastname.setText("Last name");

        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });

        lblemail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblemail.setText("E-mail");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        lblcontactnumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactnumber.setText("Contact number");

        lblssn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblssn.setText("SSN");

        lblgpslocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblgpslocation.setText("GPS location");

        lblcity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcity.setText("City");

        lblstate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblstate.setText("State");

        lblcountry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcountry.setText("Country");

        lbldriver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbldriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldriver.setText("Driver details");

        lbldriverlicence.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldriverlicence.setText("Driving licence number");

        lblserial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblserial.setText("Serial");

        lblvehicletype.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblvehicletype.setText("vehicle type");

        lblvehicle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblvehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvehicle.setText("Vehicle Registration");

        lblregistration.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblregistration.setText("Registration number");

        lblregistrationdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblregistrationdate.setText("Registration date");

        lblmodel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblmodel.setText("Model");

        lblcountry1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcountry1.setText("Coverage type");

        lblcountry2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcountry2.setText("Benefits");

        txtbenefits.setColumns(20);
        txtbenefits.setRows(5);
        jScrollPane1.setViewportView(txtbenefits);

        lblgpslocation1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblgpslocation1.setText("Corporate ID number");

        lbladdress2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbladdress2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladdress2.setText("Insurance coverage");

        lblcity1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcity1.setText("Company name");

        txtcorporateid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorporateidActionPerformed(evt);
            }
        });

        lblwebsiteurl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblwebsiteurl1.setText("Any allergies");

        lbldateofbirth1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldateofbirth1.setText("On medication");

        lblcontactnumber1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactnumber1.setText("Date of last visit");

        lblstate1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblstate1.setText("premium");

        lblcountry3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcountry3.setText("Deductable");

        lblssn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblssn1.setText("Date of next appointment");

        lbladdress1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbladdress1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladdress1.setText("Patient's Information");

        lblcontactnumber2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactnumber2.setText("Patient ID");

        lblcontactnumber3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactnumber3.setText("Insurance coverage");

        lblcontactnumber4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactnumber4.setText("Primary Doctor");

        txtdoclast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdoclastActionPerformed(evt);
            }
        });

        lblperson2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblperson2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblperson2.setText("Doctor's Information");

        lblcontactnumber5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactnumber5.setText("Contact number");

        lbllastname1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbllastname1.setText("Last name");

        lblemail1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblemail1.setText("Doctor ID");

        txtdocemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocemailActionPerformed(evt);
            }
        });

        lblemail2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblemail2.setText("E-mail");

        lblfirstname1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblfirstname1.setText("First name");

        lblspeciality.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblspeciality.setText("Speciality");

        lbloccupation1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbloccupation1.setText("Office address");

        txtdocspeciality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocspecialityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblemail)
                                                .addGap(68, 68, 68))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lbllastname, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblcontactnumber, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblssn, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtcontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblfirstname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldateofbirth)
                                    .addComponent(lblgender)
                                    .addComponent(lblnationality)
                                    .addComponent(lblwebsiteurl)
                                    .addComponent(lbloccupation))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnationality, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtwebsiteurl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(txtoccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(txtdateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblperson1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblcity)
                                            .addComponent(lblgpslocation))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtcity)
                                            .addComponent(txtgpslocation, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblcountry)
                                            .addComponent(lblstate))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtcountry)
                                            .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblregistration)
                                    .addComponent(lblserial)
                                    .addComponent(lblmodel)
                                    .addComponent(lblvehicletype)
                                    .addComponent(lblregistrationdate))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtregistrationdate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtregistrationno, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtvehicletype, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtserial, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbldriverlicence)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtdriverlicence))
                                .addComponent(lbldriver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbladdress1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblcontactnumber2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtpatientid, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblcontactnumber4)
                                            .addGap(80, 80, 80)
                                            .addComponent(txtprimarydoc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblcontactnumber1)
                                                .addComponent(lblssn1))
                                            .addComponent(lblcontactnumber3)
                                            .addComponent(lbldateofbirth1)
                                            .addComponent(lblwebsiteurl1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtnextapp, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtinsurancecover, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtlastvisit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtallergies, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmedicate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbladdress2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcountry2)
                                    .addComponent(lblcountry1))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcoveragetype)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcity1)
                                    .addComponent(lblgpslocation1)
                                    .addComponent(lblcountry3)
                                    .addComponent(lblstate1))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpremium, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtdeductable)
                                    .addComponent(txtcompanyname)
                                    .addComponent(txtcorporateid, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblemail2)
                                            .addGap(302, 302, 302))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbloccupation1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblcontactnumber5, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(215, 215, 215)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lbllastname1)
                                                            .addComponent(lblfirstname1))
                                                        .addGap(67, 67, 67))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(lblemail1)
                                                        .addGap(72, 72, 72)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtdoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtdocfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtdoclast, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtdocemail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtdoccontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtofficeadd, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtdocspeciality, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(lblspeciality))
                                        .addGap(172, 172, 172))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblperson2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbldriver, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbldriverlicence)
                                    .addComponent(txtdriverlicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblregistration)
                                    .addComponent(txtregistrationno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblregistrationdate)
                                    .addComponent(txtregistrationdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtvehicletype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblvehicletype))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblmodel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtserial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblserial)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblperson1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblfirstname)
                                            .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbllastname)
                                            .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblemail))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtcontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblcontactnumber))
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblssn)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblwebsiteurl)
                                                    .addComponent(txtwebsiteurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lbldateofbirth)
                                                    .addComponent(txtdateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblgender)
                                                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtoccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbloccupation)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(lblgpslocation)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lblcity))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtgpslocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(lblstate)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lblcountry))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtcountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtnationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblnationality)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(247, 247, 247)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbladdress2)
                            .addComponent(lbladdress1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblgpslocation1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblcity1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtcorporateid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblstate1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtdeductable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcountry3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcoveragetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcountry1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcountry2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpatientid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcontactnumber2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(txtprimarydoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblcontactnumber4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtlastvisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcontactnumber1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnextapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblssn1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(lbldateofbirth1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtallergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblwebsiteurl1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtmedicate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtinsurancecover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcontactnumber3))))
                        .addGap(198, 198, 198))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblperson2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblemail1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdocfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfirstname1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdoclast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbllastname1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtdocemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdoccontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtofficeadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdocspeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblemail2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblcontactnumber5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbloccupation1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblspeciality)))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnationalityActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtcorporateidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorporateidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorporateidActionPerformed

    private void txtdoclastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdoclastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdoclastActionPerformed

    private void txtdocemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocemailActionPerformed

    private void txtdocspecialityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocspecialityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocspecialityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lbladdress1;
    private javax.swing.JLabel lbladdress2;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblcity1;
    private javax.swing.JLabel lblcontactnumber;
    private javax.swing.JLabel lblcontactnumber1;
    private javax.swing.JLabel lblcontactnumber2;
    private javax.swing.JLabel lblcontactnumber3;
    private javax.swing.JLabel lblcontactnumber4;
    private javax.swing.JLabel lblcontactnumber5;
    private javax.swing.JLabel lblcountry;
    private javax.swing.JLabel lblcountry1;
    private javax.swing.JLabel lblcountry2;
    private javax.swing.JLabel lblcountry3;
    private javax.swing.JLabel lbldateofbirth;
    private javax.swing.JLabel lbldateofbirth1;
    private javax.swing.JLabel lbldriver;
    private javax.swing.JLabel lbldriverlicence;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblemail1;
    private javax.swing.JLabel lblemail2;
    private javax.swing.JLabel lblfirstname;
    private javax.swing.JLabel lblfirstname1;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblgpslocation;
    private javax.swing.JLabel lblgpslocation1;
    private javax.swing.JLabel lbllastname;
    private javax.swing.JLabel lbllastname1;
    private javax.swing.JLabel lblmodel;
    private javax.swing.JLabel lblnationality;
    private javax.swing.JLabel lbloccupation;
    private javax.swing.JLabel lbloccupation1;
    private javax.swing.JLabel lblperson1;
    private javax.swing.JLabel lblperson2;
    private javax.swing.JLabel lblregistration;
    private javax.swing.JLabel lblregistrationdate;
    private javax.swing.JLabel lblserial;
    private javax.swing.JLabel lblspeciality;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lblssn1;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblstate1;
    private javax.swing.JLabel lblvehicle;
    private javax.swing.JLabel lblvehicletype;
    private javax.swing.JLabel lblwebsiteurl;
    private javax.swing.JLabel lblwebsiteurl1;
    private javax.swing.JTextField txtallergies;
    private javax.swing.JTextArea txtbenefits;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcompanyname;
    private javax.swing.JTextField txtcontactnumber;
    private javax.swing.JTextField txtcorporateid;
    private javax.swing.JTextField txtcountry;
    private javax.swing.JTextField txtcoveragetype;
    private javax.swing.JTextField txtdateofbirth;
    private javax.swing.JTextField txtdeductable;
    private javax.swing.JTextField txtdoccontactnumber;
    private javax.swing.JTextField txtdocemail;
    private javax.swing.JTextField txtdocfirst;
    private javax.swing.JTextField txtdoclast;
    private javax.swing.JTextField txtdocspeciality;
    private javax.swing.JTextField txtdoctorid;
    private javax.swing.JTextField txtdriverlicence;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtgpslocation;
    private javax.swing.JTextField txtinsurancecover;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtlastvisit;
    private javax.swing.JTextField txtmedicate;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtnationality;
    private javax.swing.JTextField txtnextapp;
    private javax.swing.JTextField txtoccupation;
    private javax.swing.JTextField txtofficeadd;
    private javax.swing.JTextField txtpatientid;
    private javax.swing.JTextField txtpremium;
    private javax.swing.JTextField txtprimarydoc;
    private javax.swing.JTextField txtregistrationdate;
    private javax.swing.JTextField txtregistrationno;
    private javax.swing.JTextField txtserial;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtvehicletype;
    private javax.swing.JTextField txtwebsiteurl;
    // End of variables declaration//GEN-END:variables

    private void displayperson() {
        txtfirstname.setText(person.getFirstname());
        txtlastname.setText(person.getLastname());
        txtcontactnumber.setText(person.getContactnumber());
        txtemail.setText(person.getEmail());
        txtssn.setText(person.getSsn());
        txtnationality.setText(person.getNationality());
        txtoccupation.setText(person.getOccupation());
        txtwebsiteurl.setText(person.getWebsiteurl());
        txtdateofbirth.setText(person.getDateofbirth());
        txtgender.setText(person.getGender());

    }

    private void displaydriver() {
        txtdriverlicence.setText(driver.getDriverslicense());
    }

    private void displayaddress() {
        txtgpslocation.setText(address.getGpslocation());
        txtcity.setText(address.getCity());
        txtstate.setText(address.getState());
        txtcountry.setText(address.getCountry());
    }

    private void displayinsurancecover() {
        txtcorporateid.setText(insurancecover.getCorpid());
        txtcompanyname.setText(insurancecover.getComname());
        txtpremium.setText(insurancecover.getPremium());
        txtdeductable.setText(insurancecover.getDeductable());
        txtbenefits.setText(insurancecover.getBenefit());
        txtcoveragetype.setText(insurancecover.getCoveragetype());
    }

    private void displaypatient() {
        txtpatientid.setText(patient.getPatientid());
        txtprimarydoc.setText(patient.getPrimarydoc());
        txtlastvisit.setText(patient.getLastvisit());
        txtnextapp.setText(patient.getNextapp());
        txtmedicate.setText(patient.getMedication());
        txtallergies.setText(patient.getAllergies());
    }

    private void displayvehicle() {
        txtregistrationno.setText(vehicle.getRegnumber());
        txtserial.setText(vehicle.getSerial());
        txtmodel.setText(vehicle.getModel());
        txtregistrationdate.setText(vehicle.getRegdate());
        txtvehicletype.setText(vehicle.getVehicletype());
    }

    private void displaydoctor() {
        txtdocfirst.setText(doctor.getDocfirst());
        txtdoclast.setText(doctor.getDoclast());
        txtdocemail.setText(doctor.getDocemail());
        txtofficeadd.setText(doctor.getOfficeadd());
        txtdoctorid.setText(doctor.getDoctorid());
        txtdocspeciality.setText(doctor.getSpeciality());
    }
}
