/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.patient;

/**
 *
 * @author YAGNIK
 */
public class patientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form patientJPanel
     */
    patient patient;
    public patientJPanel(patient patient) {
        initComponents();
        this.patient = patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsave = new javax.swing.JButton();
        lblwebsiteurl = new javax.swing.JLabel();
        lbldateofbirth = new javax.swing.JLabel();
        lblcontactnumber = new javax.swing.JLabel();
        txtlastvisit = new javax.swing.JTextField();
        lblssn = new javax.swing.JLabel();
        txtnextapp = new javax.swing.JTextField();
        lbladdress = new javax.swing.JLabel();
        lblcontactnumber1 = new javax.swing.JLabel();
        txtpatientid = new javax.swing.JTextField();
        lblcontactnumber2 = new javax.swing.JLabel();
        txtinsurancecover = new javax.swing.JTextField();
        lblcontactnumber3 = new javax.swing.JLabel();
        txtprimarydoc = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnsave1 = new javax.swing.JButton();
        txtallergies = new javax.swing.JTextField();
        txtmedicate = new javax.swing.JTextField();

        btnsave.setText("Save");

        setBackground(new java.awt.Color(204, 204, 255));

        lblwebsiteurl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblwebsiteurl.setText("Any allergies");

        lbldateofbirth.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldateofbirth.setText("On medication");

        lblcontactnumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactnumber.setText("Date of last visit");

        lblssn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblssn.setText("Date of next appointment");

        lbladdress.setBackground(new java.awt.Color(204, 204, 255));
        lbladdress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbladdress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladdress.setText("Patient's Information");

        lblcontactnumber1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactnumber1.setText("Patient ID");

        lblcontactnumber2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactnumber2.setText("Insurance coverage");

        lblcontactnumber3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactnumber3.setText("Primary Doctor");

        btnsave1.setText("Save");
        btnsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbladdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblcontactnumber1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtpatientid, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblcontactnumber3)
                                    .addGap(80, 80, 80)
                                    .addComponent(txtprimarydoc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblcontactnumber)
                                        .addComponent(lblssn))
                                    .addComponent(lblcontactnumber2)
                                    .addComponent(lbldateofbirth)
                                    .addComponent(lblwebsiteurl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnextapp, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtinsurancecover, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlastvisit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtallergies, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmedicate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 766, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnsave1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbladdress)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblcontactnumber1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpatientid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtprimarydoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblcontactnumber3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlastvisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcontactnumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnextapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblssn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbldateofbirth))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtallergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblwebsiteurl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmedicate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtinsurancecover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcontactnumber2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsave1)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave1ActionPerformed
        // TODO add your handling code here:
        patient.setPatientid(txtpatientid.getText());
        patient.setPrimarydoc(txtprimarydoc.getText());
        patient.setLastvisit(txtlastvisit.getText());
        patient.setNextapp(txtnextapp.getText());
        patient.setAllergies(txtallergies.getText());
        patient.setMedication(txtmedicate.getText());
        
        JOptionPane.showMessageDialog(this,"saved successfully.");
    }//GEN-LAST:event_btnsave1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsave1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblcontactnumber;
    private javax.swing.JLabel lblcontactnumber1;
    private javax.swing.JLabel lblcontactnumber2;
    private javax.swing.JLabel lblcontactnumber3;
    private javax.swing.JLabel lbldateofbirth;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lblwebsiteurl;
    private javax.swing.JTextField txtallergies;
    private javax.swing.JTextField txtinsurancecover;
    private javax.swing.JTextField txtlastvisit;
    private javax.swing.JTextField txtmedicate;
    private javax.swing.JTextField txtnextapp;
    private javax.swing.JTextField txtpatientid;
    private javax.swing.JTextField txtprimarydoc;
    // End of variables declaration//GEN-END:variables
}
