/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.vehicle_registration;

/**
 *
 * @author YAGNIK
 */
public class vehicleregistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form vehicleregistrationJPanel
     */
    vehicle_registration vehicle;
    public vehicleregistrationJPanel(vehicle_registration Vehicle) {
        initComponents();
        this.vehicle = Vehicle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtvehicletype = new javax.swing.JTextField();
        txtmodel = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        lblvehicle = new javax.swing.JLabel();
        lblregistration = new javax.swing.JLabel();
        lblregistrationdate = new javax.swing.JLabel();
        txtregistrationno = new javax.swing.JTextField();
        txtregistrationdate = new javax.swing.JTextField();
        lblmodel = new javax.swing.JLabel();
        lblserial = new javax.swing.JLabel();
        txtserial = new javax.swing.JTextField();
        lblvehicletype = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        lblvehicle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblvehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvehicle.setText("Vehicle Registration");

        lblregistration.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblregistration.setText("Registration number");

        lblregistrationdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblregistrationdate.setText("Registration date");

        lblmodel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblmodel.setText("Model");

        lblserial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblserial.setText("Serial");

        lblvehicletype.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblvehicletype.setText("vehicle type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(btnsave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblregistration)
                                    .addComponent(lblregistrationdate))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblserial)
                                    .addComponent(lblmodel)))
                            .addComponent(lblvehicletype))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtvehicletype, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txtregistrationdate, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txtregistrationno, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txtmodel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txtserial))
                        .addContainerGap(146, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblvehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblvehicle)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblregistration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblregistrationdate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtregistrationno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtregistrationdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvehicletype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblvehicletype))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmodel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtserial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblserial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsave)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        vehicle.setRegnumber(txtregistrationno.getText());
        vehicle.setRegdate(txtregistrationdate.getText());
        vehicle.setModel(txtmodel.getText());
        vehicle.setSerial(txtserial.getText());
        vehicle.setVehicletype(txtvehicletype.getText());
        
        JOptionPane.showMessageDialog(this,"saved successfully.");
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblmodel;
    private javax.swing.JLabel lblregistration;
    private javax.swing.JLabel lblregistrationdate;
    private javax.swing.JLabel lblserial;
    private javax.swing.JLabel lblvehicle;
    private javax.swing.JLabel lblvehicletype;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtregistrationdate;
    private javax.swing.JTextField txtregistrationno;
    private javax.swing.JTextField txtserial;
    private javax.swing.JTextField txtvehicletype;
    // End of variables declaration//GEN-END:variables
}
