/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author YAGNIK
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListJPanel
     */
    private JPanel workarea;
    private Person person;
    private PersonDirectory personDirectory;
    
    



    AdminJPanel(JPanel workarea, Person person, PersonDirectory personDirectory) {
        initComponents();
        this.workarea = workarea;
        this.personDirectory = personDirectory;
        this.person = person;
        
        populateTable();      }

    
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblAccounts.getModel();
        dtm.setRowCount(0);
        for (Person person : personDirectory.getPersonlist()) {
        Object[] row = new Object[4]; 

        row[0] = person;
        row[1] = person.getName();
        row[2] = person.getNEUID();
        row[3] = person.getPassword();
        
        dtm.addRow(row);
            
        }

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccounts = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        deletebtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        searchneuidtxt = new javax.swing.JTextField();
        viewbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 204, 255));

        tblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "USERID", "NAME", "NEUID", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblAccounts);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN ACCESS");

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        searchbtn.setText("Search NEUID");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        viewbtn.setText("View Details");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(deletebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchneuidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbtn)
                    .addComponent(searchneuidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(viewbtn)
                .addGap(18, 18, 18)
                .addComponent(deletebtn)
                .addGap(137, 137, 137)
                .addComponent(backbtn)
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
String NEUIDString = searchneuidtxt.getText();

// Assuming personDirectory.searchPerson returns a Person object based on NEUID
Person person = personDirectory.searchPerson(NEUIDString);
if (person == null) {
    JOptionPane.showMessageDialog(null, "Person with NEUID " + NEUIDString + " not found");
} else {
    String stringNEUID = "yourStringValue"; // Replace with the NEUID you want to compare with

    String personNEUID = person.getNEUID();
    if (personNEUID != null && personNEUID.equals(stringNEUID)) {
        ViewDetailsJPanel viewDetails = new ViewDetailsJPanel(workarea, person);
        workarea.add("ViewDetailsJPanel", viewDetails);
        CardLayout layout = (CardLayout) workarea.getLayout();
        layout.next(workarea);       
    } else {
        JOptionPane.showMessageDialog(null, "Person NEUID does not match: " + NEUIDString);
    }
}


    }//GEN-LAST:event_searchbtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
    int selectedRow = tblAccounts.getSelectedRow();
    if(selectedRow<0){
        JOptionPane.showMessageDialog(null, "Please select a row from the table first");
        
    }
    else{
        Person person = (Person) tblAccounts.getValueAt(selectedRow, 0);
        ViewDetailsJPanel viewDetails = new ViewDetailsJPanel(workarea, person);
        workarea.add("ViewDetailsJPanel", viewDetails);
        CardLayout layout = (CardLayout) workarea.getLayout();
        layout.next(workarea);    
    }
        
        
    }//GEN-LAST:event_viewbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        CardLayout cardLayout = (CardLayout) workarea.getLayout();
        cardLayout.previous(workarea);
    }//GEN-LAST:event_backbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
    int selectedRow = tblAccounts.getSelectedRow();
    
    if (selectedRow >= 0) {
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "would you like to delete this person details?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            Person person = (Person) tblAccounts.getValueAt(selectedRow, 0);
            personDirectory.deletePerson(person);
            populateTable();
        }
    } 
    else {
        JOptionPane.showMessageDialog(null, "Please select a row from the table first");
    }//GEN-LAST:event_deletebtnActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchneuidtxt;
    private javax.swing.JTable tblAccounts;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
